### ISSUE TITLE
Add to melpa / How does it differ from old muttrc-el in the emacs wiki?

### ISSUE THREAD

**Issue by Knusper** [neomutt/muttrc-mode-el#1]
Previously one could install https://www.emacswiki.org/emacs/muttrc-mode.el via the emacs package manager from  the MELPA repository. Since MELPA does not include packages from the emacswiki anymore, because of [security concerns][1],  this is not possible anymore.

Given that now a similar package appears to be maintained on github, which is considered a trusworthy source for MELPA, I would strongly encourage you to [add the package to MELPA][2].

Moreover, could add information regarding the key differences between this package and the old muttrc-el from the emacswiki?

[1]: https://github.com/melpa/melpa/pull/5008
[2]: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org

**Comment by Knusper** [comment]
Non of my questions was answered and the package got not added to melpa.  I thus friendly inquire,  why this bug report got closed as completed?

**Comment by flatcap** [comment]
Back when I closed this issue, GitHub didn't distinguish between "Closed completed" and "Closed won't fix".

I don't use, or understand,; Emacs.
I "closed" the issue because after two years nobody had commented on it.
